name: ViT_local
channels:
  - pytorch
  - huggingface
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.10
  - aiofiles
  - aiohappyeyeballs
  - aiohttp
  - aiosignal
  - altair
  - annotated-types
  - anyio
  - aom
  - appdirs
  - appnope
  - arrow
  - arrow-cpp
  - asttokens
  - attrs
  - aws-c-auth
  - aws-c-cal
  - aws-c-common
  - aws-c-compression
  - aws-c-event-stream
  - aws-c-http
  - aws-c-io
  - aws-c-mqtt
  - aws-c-s3
  - aws-c-sdkutils
  - aws-checksums
  - aws-crt-cpp
  - aws-sdk-cpp
  - binaryornot
  - blas
  - blosc
  - boost-cpp
  - bottleneck
  - brotli
  - brotli-python
  - brunsli
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cfitsio
  - chardet
  - charls
  - charset-normalizer
  - click
  - comm
  - contourpy
  - cookiecutter
  - cycler
  - cyrus-sasl
  - dataclasses
  - datasets
  - dav1d
  - debugpy
  - decorator
  - dill
  - dnspython
  - docker-pycreds
  - eigen
  - email-validator
  - email_validator
  - eval-type-backport
  - eval_type_backport
  - evaluate
  - exceptiongroup
  - executing
  - expat
  - fastapi
  - fastapi-cli
  - ffmpeg
  - ffmpy
  - filelock
  - fontconfig
  - fonttools
  - freetype
  - fribidi
  - frozenlist
  - fsspec
  - gdk-pixbuf
  - gettext
  - gflags
  - giflib
  - gitdb
  - gitpython
  - glib
  - glib-tools
  - glog
  - gmp
  - gmpy2
  - gnutls
  - gradio
  - gradio-client
  - graphite2
  - gst-plugins-base
  - gstreamer
  - h11
  - h2
  - harfbuzz
  - hdf5
  - hpack
  - httpcore
  - httptools
  - httpx
  - huggingface_hub
  - hyperframe
  - icu
  - idna
  - imagecodecs
  - imageio
  - importlib-metadata
  - importlib_resources
  - ipykernel
  - ipython
  - ipython_pygments_lexers
  - jedi
  - jinja2
  - jpeg
  - jsonschema
  - jsonschema-specifications
  - jupyter_client
  - jupyter_core
  - jxrlib
  - kiwisolver
  - krb5
  - lame
  - lazy-loader
  - lazy_loader
  - lcms2
  - leptonica
  - lerc
  - libabseil
  - libaec
  - libarchive
  - libavif
  - libboost
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libclang
  - libclang13
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libevent
  - libffi
  - libgfortran
  - libgfortran5
  - libglib
  - libgrpc
  - libiconv
  - libjpeg-turbo
  - libllvm14
  - libnghttp2
  - libntlm
  - libogg
  - libopenblas
  - libopus
  - libpng
  - libpq
  - libprotobuf
  - librsvg
  - libsodium
  - libssh2
  - libtheora
  - libthrift
  - libtiff
  - libuv
  - libvorbis
  - libvpx
  - libwebp
  - libwebp-base
  - libxml2
  - libzopfli
  - lightning-utilities
  - linkify-it-py
  - llvm-openmp
  - lz4-c
  - markdown-it-py
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mdit-py-plugins
  - mdurl
  - mpc
  - mpfr
  - mpmath
  - multidict
  - multiprocess
  - mysql
  - narwhals
  - ncurses
  - nest-asyncio
  - nettle
  - networkx
  - numexpr
  - numpy
  - numpy-base
  - opencv
  - openh264
  - openjpeg
  - openldap
  - openssl
  - orc
  - orjson
  - packaging
  - pandas
  - pango
  - parso
  - pcre2
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - pkgutil-resolve-name
  - platformdirs
  - prompt-toolkit
  - propcache
  - protobuf
  - psutil
  - ptyprocess
  - pure_eval
  - pyarrow
  - pydantic
  - pydantic-core
  - pydub
  - pygments
  - pyparsing
  - pysocks
  - python-dateutil
  - python-dotenv
  - python-multipart
  - python-slugify
  - python-tzdata
  - python-xxhash
  - pytorch
  - pytz
  - pyyaml
  - pyzmq
  - qt-main
  - re2
  - readline
  - referencing
  - regex
  - requests
  - rich
  - rich-toolkit
  - rpds-py
  - safetensors
  - scikit-image
  - scipy
  - semantic_version
  - sentry-sdk
  - setproctitle
  - setuptools
  - shellingham
  - six
  - smmap
  - snappy
  - sniffio
  - sqlite
  - stack_data
  - starlette
  - tesseract
  - text-unidecode
  - tifffile
  - tk
  - tokenizers
  - tomli
  - torchmetrics
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - transformers
  - typer
  - typer-slim
  - typer-slim-standard
  - types-python-dateutil
  - typing-extensions
  - typing_extensions
  - tzdata
  - uc-micro-py
  - unicodedata2
  - urllib3
  - utf8proc
  - uvicorn
  - uvicorn-standard
  - uvloop
  - wandb
  - watchfiles
  - wcwidth
  - websockets
  - wheel
  - x264
  - xxhash
  - xz
  - yaml
  - yarl
  - zeromq
  - zfp
  - zipp
  - zlib
  - zlib-ng
  - zstd
  - pip:
      - accelerate
      - albucore
      - albumentations
      - joblib
      - scikit-learn
      - simsimd
      - stringzilla
      - sympy
      - threadpoolctl

