name: ViT_local
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.2.2
  - torchvision=0.17.2
  - torchaudio=2.2.2
  - albumentations=1.3.1
  - scikit-learn=1.4.2
  - matplotlib=3.8.4
  - pandas=2.2.2
  - tqdm=4.66.2
  - ipykernel=6.29.4
  - fastapi=0.110.0
  - uvicorn=0.29.0
  - transformers=4.40.1
  - datasets=2.19.1
  - gradio=4.23.0
  - wandb=0.16.6
  - pip
  - pip:
      - albucore==0.0.23
      - simsimd==6.2.1
      - stringzilla==3.12.5
